image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:
  SERVER_TEST_IMAGE: karuban88/bpwjs-server:$CI_COMMIT_REF_NAME
  SERVER_RELEASE_IMAGE: karuban88/bpwjs-server:latest

before_script:
  - docker login -u karuban88 -p $CI_DOCKERHUB_PASSWORD

build-server:
  stage: build
  script:
    - docker build --pull -t $SERVER_TEST_IMAGE ./server
    - docker push $SERVER_TEST_IMAGE

test-server:
  stage: test
  script:
    - docker pull $SERVER_TEST_IMAGE
    - docker run $SERVER_TEST_IMAGE npm test

release-image:
  stage: release
  script:
    - docker pull $SERVER_TEST_IMAGE
    - docker tag $SERVER_TEST_IMAGE $SERVER_RELEASE_IMAGE
    - docker push $SERVER_RELEASE_IMAGE
  only:
    - master